const msg_bom_dia = [
  "Que seu dia seja brilhante como o sol! ??",
  "Hoje é um novo dia para ser incrível! ??",
  "Que a paz e o amor guiem seu dia! ??",
  "Desperte com um sorriso no rosto! ??",
  "Que a alegria esteja com você hoje e sempre! ??",
  "Aproveite cada momento deste novo dia! ??",
  "Que seu dia seja leve e cheio de boas energias! ??",
  "Hoje é um ótimo dia para ser feliz! ??",
  "Que seu coração esteja cheio de gratidão! ??",
  "Que a luz do sol ilumine seu caminho! ??",
  "Que seu dia seja tão especial quanto você! ??",
  "Acredite no poder de um novo começo! ??",
  "Que seu dia seja repleto de sorrisos! ??",
  "Hoje é um dia para conquistar seus sonhos! ??",
  "Que a felicidade bata à sua porta! ??",
  "Que seu dia seja cheio de amor e paz! ??",
  "Desperte com o coração cheio de esperança! ??",
  "Que seu dia seja tão brilhante quanto você! ?",
  "Hoje é um dia para ser grato e feliz! ??",
  "Que seu dia seja cheio de pequenas alegrias! ??",
  "Que a energia positiva esteja com você! ??",
  "Hoje é um dia para espalhar amor e bondade! ??",
  "Que seu dia seja tão doce quanto você! ??",
  "Que a paz esteja com você hoje e sempre! ???",
  "Hoje é um dia para brilhar! ??",
  "Que seu dia seja cheio de boas surpresas! ??",
  "Que a felicidade esteja em cada detalhe do seu dia! ??",
  "Hoje é um dia para ser incrível! ??",
  "Que seu dia seja cheio de amor e luz! ??",
  "Que seu dia seja tão especial quanto você! ??",
  "Hoje é um dia para ser grato e feliz! ??",
  "Que seu dia seja cheio de pequenas alegrias! ??",
  "Que a energia positiva esteja com você! ??",
  "Hoje é um dia para espalhar amor e bondade! ??",
  "Que seu dia seja tão doce quanto você! ??",
  "Que a paz esteja com você hoje e sempre! ???",
  "Hoje é um dia para brilhar! ??",
  "Que seu dia seja cheio de boas surpresas! ??",
  "Que a felicidade esteja em cada detalhe do seu dia! ??",
  "Hoje é um dia para ser incrível! ??",
  "Que seu dia seja cheio de amor e luz! ??",
  "Que seu dia seja tão especial quanto você! ??",
  "Hoje é um dia para ser grato e feliz! ??",
  "Que seu dia seja cheio de pequenas alegrias! ??",
  "Que a energia positiva esteja com você! ??",
  "Hoje é um dia para espalhar amor e bondade! ??",
  "Que seu dia seja tão doce quanto você! ??",
  "Que a paz esteja com você hoje e sempre! ???",
  "Hoje é um dia para brilhar! ??",
  "Que seu dia seja cheio de boas surpresas! ??"
];

module.exports = {
  msg_bom_dia
}