const msg_bom_dia = [
  "Que seu dia seja brilhante como o sol! ☀️",
  "Hoje é um novo dia para ser incrível! 🌟",
  "Que a paz e o amor guiem seu dia! 💖",
  "Desperte com um sorriso no rosto! 😊",
  "Que a alegria esteja com você hoje e sempre! 🎉",
  "Aproveite cada momento deste novo dia! 🌈",
  "Que seu dia seja leve e cheio de boas energias! 🌿",
  "Hoje é um ótimo dia para ser feliz! 😄",
  "Que seu coração esteja cheio de gratidão! ❤️",
  "Que a luz do sol ilumine seu caminho! 🌞",
  "Que seu dia seja tão especial quanto você! 🌸",
  "Acredite no poder de um novo começo! 🌱",
  "Que seu dia seja repleto de sorrisos! 😁",
  "Hoje é um dia para conquistar seus sonhos! 🚀",
  "Que a felicidade bata à sua porta! 🏡",
  "Que seu dia seja cheio de amor e paz! 💕",
  "Desperte com o coração cheio de esperança! 🌻",
  "Que seu dia seja tão brilhante quanto você! ✨",
  "Hoje é um dia para ser grato e feliz! 🙏",
  "Que seu dia seja cheio de pequenas alegrias! 🎈",
  "Que a energia positiva esteja com você! 🔋",
  "Hoje é um dia para espalhar amor e bondade! 💝",
  "Que seu dia seja tão doce quanto você! 🍯",
  "Que a paz esteja com você hoje e sempre! 🕊️",
  "Hoje é um dia para brilhar! 🌟",
  "Que seu dia seja cheio de boas surpresas! 🎁",
  "Que a felicidade esteja em cada detalhe do seu dia! 😊",
  "Hoje é um dia para ser incrível! 🌈",
  "Que seu dia seja cheio de amor e luz! 💡",
  "Que seu dia seja tão especial quanto você! 🌸",
  "Hoje é um dia para ser grato e feliz! 🙏",
  "Que seu dia seja cheio de pequenas alegrias! 🎈",
  "Que a energia positiva esteja com você! 🔋",
  "Hoje é um dia para espalhar amor e bondade! 💝",
  "Que seu dia seja tão doce quanto você! 🍯",
  "Que a paz esteja com você hoje e sempre! 🕊️",
  "Hoje é um dia para brilhar! 🌟",
  "Que seu dia seja cheio de boas surpresas! 🎁",
  "Que a felicidade esteja em cada detalhe do seu dia! 😊",
  "Hoje é um dia para ser incrível! 🌈",
  "Que seu dia seja cheio de amor e luz! 💡",
  "Que seu dia seja tão especial quanto você! 🌸",
  "Hoje é um dia para ser grato e feliz! 🙏",
  "Que seu dia seja cheio de pequenas alegrias! 🎈",
  "Que a energia positiva esteja com você! 🔋",
  "Hoje é um dia para espalhar amor e bondade! 💝",
  "Que seu dia seja tão doce quanto você! 🍯",
  "Que a paz esteja com você hoje e sempre! 🕊️",
  "Hoje é um dia para brilhar! 🌟",
  "Que seu dia seja cheio de boas surpresas! 🎁"
];

const msg_noticias_preambulo = [
  "Comece o dia bem informado com as notícias a seguir:",
  "Leia as notícias de hoje e avise seus amigos que foi um bot quem te informou (jura):",
  "Pronto para se atualizar? As notícias quentinhas já chegaram!",
  "Notícias fresquinhas, como pão saído do forno. Aproveite!",
  "Se o dia fosse um filme, essas notícias seriam os spoilers que você precisa!",
  "Notícias quentes, mas sem queimar os dedos. Vamos lá!",
  "Prepare o café e se acomode, porque as notícias estão prontas para você:",
  "Se informação fosse vitamina, você estaria prestes a ficar super saudável...!",
  "Notícias frescas, direto da redação para o seu cérebro curioso:",
  "Hoje tem notícia boa, ruim e aquela que vai te deixar pensando. Duvida? Pois eu também.",
  "Notícias que valem mais que um like. Dê uma olhada:",
  "As melhores chamadas da imprensa hoje estão aqui no nosso resumo diário:",
  "Se o mundo fosse um livro, essas seriam as páginas que você não pode pular:",
  "Notícias que vão te deixar mais esperto que um rato de biblioteca:",
  "Aqui estão as notícias que vão te deixar no clima de 'um bot me falou isso às 7h30min'!",
  "Notícias que vão te deixar mais informado que um papagaio tagarela.",
  "Prepare-se para uma overdose de informação (do bem, claro)!",
  "Notícias que vão te deixar mais afiado que um lápis recém-apontado:",
  "Se informação fosse dinheiro, você estaria prestes a ficar rico:",
  "Notícias que vão te deixar mais esperto que um esquilo estocado:",
  "Um copo de café, uma lista de manchetes e você recomendando o Bot Senpai pra todo mundo = Fórmula perfeita 🥰",
  "Novidades que vão te deixar mais conectado que eu em você ♥️",
  "Notícias que vão te deixar mais sabido que um rato de laboratório:",
  "Aqui estão as notícias que vão te deixar mais sabido que um cientista maluco:",
  "Notícias que vão te deixar mais esperto que um macaco de filme de ação:",
  "Prepare-se para uma dose diária de notícias que vão te deixar mais informado que velha fofoqueira!",
  "Notícias que vão te deixar mais esperto que um detetive de filme noir:",
  "Notícias que vão te deixar mais ligado que um fio de alta tensão:"
];

const msg_fato_inutil = [
  "Fato inútil do dia: ",
  "Você sabia? ",
  "Curiosidade mais aleatória do seu dia de hoje - ",
  "Acredite ou não: ",
  "Saiba antes de morrer: ",
  "Curiosidade: ",
  "Informação (ir)relevante do dia: ",
  "Pode acreditar: ",
  "Seu dia começa melhor aprendendo o fato inútil do dia: ",
  "E o fato inútil do dia hoje é: ",
  "Conhecimento sempre é importante: ",
  "Adivinha só - ",
  "Só no Bot Senpai pra você saber disso: ",
  "Se liga na curiosidade do dia: ",
  "Fato irrelevante e inútil de hoje: "
]

module.exports = {
  msg_bom_dia,
  msg_noticias_preambulo,
  msg_fato_inutil
}